# Generated by Django 5.0.6 on 2025-02-25 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='certificate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='certificate_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
