# Generated by Django 5.0.6 on 2025-02-25 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0002_profile_certificate_profile_certificate_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='certificate_description',
            new_name='certificates',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='project_description',
            new_name='languagess',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='language',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='project',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='project_link',
        ),
        migrations.AddField(
            model_name='profile',
            name='projects',
            field=models.TextField(blank=True, null=True),
        ),
    ]
