# Generated by Django 5.0.6 on 2025-03-18 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0002_remove_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='projects',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
