# Generated by Django 5.0.6 on 2025-02-25 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0004_rename_languagess_profile_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='certificates',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='languages',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='projects',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
