# Generated by Django 5.0.6 on 2025-02-25 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0006_remove_profile_certificates_remove_profile_languages_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='certificate_name',
            new_name='certificate',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='language_name',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_name',
            new_name='project',
        ),
    ]
